# Generated by Django 3.2 on 2022-03-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='body',
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
